# Generated by Django 4.0.3 on 2022-10-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
