# Generated by Django 4.0.3 on 2022-10-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_image_listing_imageurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
